## Basic Configuration
baseurl = "https://example.com/"
languageCode = "en"

title = "Poff Dev"
theme = "hyde-hyde"

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
# googleAnalytics = "your-google-analytics-id"
# enableRobotsTXT = true

# summarylength = 30

paginate = 1

## Site Settings
[params]
    author = "Author"
    title = "Poff Development"
    # description = "..."
    authorimage = "/img/hugo.png"
    dateformat = "Jan 2, 2006"
    themeColor = "theme-base-0f"
    layoutReverse = true

    # sidebar, copyright & license
    copyright = "htr3n"
    license = "CC BY-SA 4.0"
    licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
    showBuiltWith = true

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"

    # please choose either GraphComment or Disqus or Utterances
    #GraphCommentId = "..."
    #UtterancesRepo = "..." # https://utteranc.es/
    #UtterancesIssueTerm = "..." # pathname, url, title, og:title
    #UtterancesTheme = "..." # github-light or github-dark

    # Table of contents
    #toc = none, "hugo", or "tocbot"

## Social Accounts
[params.social]
    github = "<username>"
    instagram = "<username>"
    xing = "<username>"
    linkedin = "<username>"
    twitter = "<username>"
    facebook = "<username>"
    stackoverflow = "<username>"
    telegram = "<username>"
    email = "your-email@example.com"
    # gravatar = "your-email@example.com"

[taxonomies]
  category = "categories"
  tag = "tags"

  ## Main Menu

[[menu.main]]
	identifier = "about"
	name = "About me"
	url = "/about/"
	weight = 20

#[[menu.main]]
#	identifier = "posts"
#	name = "Posts"
#	url = "/posts/"
#	weight = 10

#[[menu.main]]
#  identifier = "rss"
#  name = "RSS"
#  url = "/index.xml"
#  weight = 50

[[menu.main]]
	identifier = "contact"
	name = "Contact"
	url = "/contact/"
	weight = 30
